kind: Namespace
apiVersion: v1
metadata:
  name: java-logger
  labels:
    name: java-logger
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-configmap
  namespace: java-logger
data:
  filebeat.yml: |
    processors:
    - script:
        lang: javascript
        id: add_custom_filters
        source: >
          function process(event) {
              var logFilePath = event.Get("log.file.path")
              if(logFilePath != undefined && logFilePath != null && logFilePath != ""){
                logFilePath = logFilePath.toString().replace("/home/jboss/logs/","")
                var podName = logFilePath.substring(0,logFilePath.indexOf("/"))
                var logName = logFilePath.substring(logFilePath.indexOf("/")+1, logFilePath.length)
                event.Put("logFileId", logName)
                event.Put("podName", podName)
                event.Put("clusterName", "OCP_ODF_CLUSTER_RHPDS")
              }
          }
    filebeat.inputs:
    - type: log
      paths:
        - '/home/jboss/logs/java-logger-*/app.log*'
      multiline.pattern: '^[0-9]{4}[\/-]{1}[0-9]{2}[\/-]{1}[0-9]{2}'
      multiline.negate: true
      multiline.match: after
      tags: ['systemOut']
      fields_under_root: true
      filebeat.config.modules:
        path: /opt/app-root/src/filebeat/modules.d/*.yml
        reload.enabled: true
    - type: log
      paths:
        - '/home/jboss/logs/java-logger-*/activity*.log'
        - '/home/jboss/logs/java-logger-*/ecrime*.log'
        - '/home/jboss/logs/java-logger-*/perf*.log'
        - '/home/jboss/logs/java-logger-*/reqresdata*.log'
      multiline.pattern: '^[0-9]{4}[\/-]{1}[0-9]{2}[\/-]{1}[0-9]{2}'
      multiline.negate: true
      multiline.match: after
      tags: ['BarcEvents']
      fields_under_root: true
      filebeat.config.modules:
        path: /opt/app-root/src/filebeat/modules.d/*.yml
        reload.enabled: true
    output:
      elasticsearch:
        hosts: ["https://elasticsearch-es-http.elastic-monitoring.svc.cluster.local:9200"]
        username: "elastic"
        password: "nL8Spe96gMd57T7JiSX52W40"
        ssl.verification_mode: none
    setup:
      kibana: 
        host: "kibana-kb-http.elastic-monitoring.svc.cluster.local"
    logging:
      level: debug
      to_files: true
      to_stderr: true
      to_syslog: false
      files:
        path: /var/log/filebeat
        name: filebeat
        keepfiles: 1
        permissions: 0640
    filebeat.registry:
      path: ${path.data}/registry
      file_permissions: 0640

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-logger
  name: java-logger-service
  namespace: java-logger
spec:
  ports:
    - name: 8080-tcp
      port: 8080
  selector:
    deployment: java-logger
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: java-logger-pvc
  namespace: java-logger
spec:
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  resources:
    requests:
      storage: 12Gi
  # storageClassName: thin-csi
  storageClassName: px-csi-db
---
apiVersion: apps/v1
#kind: StatefulSet
kind: Deployment
metadata:
  labels:
    app: java-logger
  name: java-logger
  namespace: java-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: java-logger
  template:
    metadata:
      labels:
        deployment: java-logger
    spec:
      containers:
        - env:
            - name: JAVA_LOGGER_EXEC_THREADS
              value: "1"
            - name: SPRING_PROFILES_ACTIVE
              value: "openshift"
            - name: K8S_CLUSTER_ID
              value: "OCP_ODF_CLUSTER_RHPDS"
            - name: JAVA_LOGGER_CONTAINER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: quay.io/ajarrett/java-logger-8:latest
          imagePullPolicy: Always
          name: java-logger
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /home/jboss/logs
              name: java-logger-pv
        - name: filebeat
          env:
          - name: K8S_CLUSTER_ID
            value: "OCP_ODF_CLUSTER_RHPDS"
          - name: JAVA_LOGGER_CONTAINER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: registry.connect.redhat.com/elastic/filebeat:7.17.1
          volumeMounts:
          - name: java-logger-pv
            mountPath: /home/jboss/logs
          - name: filebeat-config
            mountPath: /usr/share/filebeat/filebeat.yml
            subPath: filebeat.yml
#      securityContext:
#        allowPrivilegeEscalation: true
      volumes:
        - name: java-logger-pv
          persistentVolumeClaim:
            claimName: java-logger-pvc
        - name: filebeat-config
          configMap:
            name: filebeat-configmap
            items:
              - key: filebeat.yml
                path: filebeat.yml
#  volumeClaimTemplates:
#    - metadata:
#        name: java-logger-vol
#      spec:
#        accessModes:
#          - ReadWriteOnce
#        resources:
#          requests:
#            storage: 3Gi
#        storageClassName: ocs-storagecluster-cephfs
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: java-logger
  name: java-logger
  namespace: java-logger
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: java-logger-service
    weight: 100
  wildcardPolicy: None