apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-logger
  name: java-logger-service
spec:
  ports:
    - name: 8080-tcp
      port: 8080
  selector:
    deployment: java-logger
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: java-logger-pvc
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  resources:
    requests:
      storage: 6Gi
  storageClassName: thin-csi
  # storageClassName: crc-csi-hostpath-provisioner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-logger
  name: java-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: java-logger
  template:
    metadata:
      labels:
        deployment: java-logger
    spec:
      containers:
        - image: quay.io/ajarrett/java-logger:latest
          imagePullPolicy: Always
          name: java-logger
          env:
            - name: JAVA_LOGGER_EXEC_THREADS
              value: 1
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /home/jboss/logs
              name: java-logger-pv
      securityContext:
        allowPrivilegeEscalation: false
      volumes:
        - name: java-logger-pv
          persistentVolumeClaim:
            claimName: java-logger-pvc
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: java-logger
  name: java-logger
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: java-logger-service
    weight: 100
  wildcardPolicy: None