kind: Namespace
apiVersion: v1
metadata:
  name: java-logger
  labels:
    name: java-logger
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-configmap
  namespace: java-logger
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - '/home/jboss/logs/app.log'
      filebeat.config.modules:
        path: /opt/app-root/src/filebeat/modules.d/*.yml
        reload.enabled: true
    output:
      elasticsearch:
        hosts: ["https://elasticsearch-es-http.elastic-monitoring.svc.cluster.local:9200"]
        username: "elastic"
        password: "58yeA0sC8orzaV8R7dR518Z2"
        ssl.verification_mode: none
    setup:
      kibana: 
        host: "kibana-kb-http-elastic-monitoring.apps.cedar.demolab.local"
    logging:
      level: debug
      to_files: true
      to_stderr: true
      to_syslog: false
      files:
        path: /var/log/filebeat
        name: filebeat
        keepfiles: 1
        permissions: 0640
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-logger
  name: java-logger-service
  namespace: java-logger
spec:
  ports:
    - name: 8080-tcp
      port: 8080
  selector:
    deployment: java-logger
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: java-logger-pvc
  namespace: java-logger
spec:
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  resources:
    requests:
      storage: 1Gi
  #storageClassName: thin-csi
  storageClassName: ocs-storagecluster-cephfs
  # storageClassName: crc-csi-hostpath-provisioner (ReadWriteOnce)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-logger
  name: java-logger
  namespace: java-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: java-logger
  template:
    metadata:
      labels:
        deployment: java-logger
    spec:
      containers:
        - env:
            - name: JAVA_LOGGER_EXEC_THREADS
              value: "1"
            - name: JAVA_LOGGER_CONTAINER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: quay.io/ajarrett/java-logger:latest
          imagePullPolicy: Always
          name: java-logger
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /home/jboss/logs
              name: java-logger-pv
        - name: filebeat
          image: registry.connect.redhat.com/elastic/filebeat:7.17.1
#          securityContext:
#            runAsUser: filebeat
#            privileged: true
          volumeMounts:
          - name: java-logger-pv
            mountPath: /home/jboss/logs
          - name: filebeat-config
            mountPath: /usr/share/filebeat/filebeat.yml
            subPath: filebeat.yml
      securityContext:
        allowPrivilegeEscalation: true
      volumes:
        - name: java-logger-pv
          persistentVolumeClaim:
            claimName: java-logger-pvc
        - name: filebeat-config
          configMap:
            name: filebeat-configmap
            items:
              - key: filebeat.yml
                path: filebeat.yml
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: java-logger
  name: java-logger
  namespace: java-logger
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: java-logger-service
    weight: 100
  wildcardPolicy: None